# This workflow builds a Java app. It will run on pull requests and
# when called from another workflow.

name: Build Java Project
on:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build-node:
    name: Build Java project
    runs-on: ubuntu-latest
#    outputs:
#      project-version: ${{ steps.project-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openj9'
          java-version: '11'

      - name: Lint
        run: echo TODO linting

      - name: Unit Test
        run: ./gradlew clean test

#      - name: Upload Coverage Report
#        uses: actions/upload-artifact@v3
#        with:
#          name: code-coverage
#          path: coverage/lcov.info
#
#      - name: Get NPM project version
#        id: project-version
#        run: echo "::set-output name=version::$(npm pkg get version | sed 's/\"//g')"
